import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mockMidi } from './midiFixture'

async function setup(page: Page) {
  await mockMidi(page)
  await page.goto('./')
  await expect(page.locator('.eyebrow')).toHaveText('ピアノ練習 · Phase 2E-D3.3')
  await expect(page.getByRole('button', { name: 'テスト音 C4' })).toBeDisabled()
  await page.getByRole('button', { name: 'MIDI接続', exact: true }).click()
  await expect(page.locator('.output-status')).toHaveText('MIDI入力：接続済み ／ MIDI出力：接続済み')
}

test('shares one permission request, sends C4 with scheduled off, and preserves input grading', async ({ page }) => {
  await setup(page)
  expect(await page.evaluate(() => window.midiTest.requests)).toBe(1)
  await expect(page.getByRole('combobox', { name: '出力機器' })).toHaveValue('cme-out')
  await page.getByRole('button', { name: 'テスト音 C4' }).click()
  await expect(page.getByTestId('latest-output')).toContainText('C4 / Note On / MIDI Note 60 / Velocity 80 / Channel 1')
  const sent = await page.evaluate(() => window.midiTest.outputMessages)
  expect(sent.map(({ data }) => data)).toEqual([[0x90, 60, 80], [0x80, 60, 0]])
  expect(sent[1].timestamp - sent[0].requestedAt).toBeGreaterThan(450)
  expect(sent[1].timestamp - sent[0].requestedAt).toBeLessThanOrEqual(500)
  await expect(page.getByTestId('latest-output')).toContainText('C4 / Note Off / MIDI Note 60 / Velocity 0 / Channel 1')
  await expect(page.locator('.position')).toHaveText('1 / 14 音')
  await expect(page.getByTestId('latest-input')).toHaveCount(0)
  await page.getByRole('button', { name: '練習開始' }).click()
  await page.getByRole('button', { name: 'テスト音 C4' }).click()
  await expect(page.locator('.position')).toHaveText('1 / 14 音')
  await page.evaluate(() => window.midiTest.send([0x90, 64, 40]))
  await expect(page.locator('.practice-feedback')).toHaveText('もう一度♪')
  await page.evaluate(() => window.midiTest.send([0x90, 60, 72]))
  await expect(page.locator('.position')).toHaveText('2 / 14 音')
  await page.evaluate(() => window.midiTest.send([0x80, 60, 0]))
  await expect(page.locator('.position')).toHaveText('2 / 14 音')
  await expect(page.getByTestId('latest-input')).toContainText('Note Off')
  await expect(page.getByTestId('latest-output')).toContainText('Note Off')
  await page.screenshot({ path: 'test-results/phase2ca-output.png', fullPage: true })
})

test('emergency stop clears scheduled output and sends Note Off plus CC123', async ({ page }) => {
  await setup(page)
  await page.getByRole('button', { name: 'テスト音 C4' }).click()
  await page.getByRole('button', { name: 'すべての音を停止' }).click()
  await expect(page.getByTestId('latest-output')).toHaveText('All Notes Off / CC 123 / Value 0 / Channel 1')
  expect(await page.evaluate(() => window.midiTest.outputMessages.slice(-2).map(({ data }) => data))).toEqual([[0x80, 60, 0], [0xb0, 123, 0]])
  expect(await page.evaluate(() => window.midiTest.outputClears)).toContain('cme-out')
  await expect(page.getByRole('button', { name: 'テスト音 C4' })).toBeEnabled()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/phase2ca-mobile.png', fullPage: true })
})

test('selects outputs independently, honors no selection, and handles unplug/reconnect without replay', async ({ page }) => {
  await setup(page)
  await page.evaluate(() => window.midiTest.setOutputConnected('other-out', true))
  const selector = page.getByRole('combobox', { name: '出力機器' })
  await selector.selectOption('other-out')
  await page.getByRole('button', { name: 'テスト音 C4' }).click()
  expect(await page.evaluate(() => window.midiTest.outputMessages[0].id)).toBe('other-out')
  await selector.selectOption('')
  await expect(page.getByRole('button', { name: 'テスト音 C4' })).toBeDisabled()
  await expect(page.locator('.output-panel')).toContainText('選択してください')
  await selector.selectOption('cme-out')
  await page.getByRole('button', { name: 'テスト音 C4' }).click()
  await page.evaluate(() => window.midiTest.setOutputConnected('cme-out', false))
  await expect(page.getByRole('button', { name: 'テスト音 C4' })).toBeDisabled()
  await expect(page.locator('.output-panel')).toContainText('切断されました')
  await expect(page.locator('.midi-status')).toHaveText('MIDI 接続中')
  const sentCount = await page.evaluate(() => window.midiTest.outputMessages.length)
  await page.evaluate(() => window.midiTest.setOutputConnected('cme-out', true))
  await expect(selector).toHaveValue('cme-out')
  await expect(page.getByRole('button', { name: 'テスト音 C4' })).toBeEnabled()
  expect(await page.evaluate(() => window.midiTest.outputMessages.length)).toBe(sentCount)
  expect(await page.evaluate(() => window.midiTest.requests)).toBe(1)
})

test('output errors can be retried without breaking input or asking for another permission', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await mockMidi(page)
  await page.goto('./')
  await page.evaluate(() => { window.midiTest.failOutputOpen = true })
  await page.getByRole('button', { name: 'MIDI接続', exact: true }).click()
  await expect(page.locator('.output-status')).toHaveText('MIDI入力：接続済み ／ MIDI出力：エラー')
  await page.evaluate(() => { window.midiTest.failOutputOpen = false })
  await page.getByRole('button', { name: '出力を再接続' }).click()
  await expect(page.getByRole('button', { name: 'テスト音 C4' })).toBeEnabled()
  await page.evaluate(() => { window.midiTest.failSend = true })
  await page.getByRole('button', { name: 'テスト音 C4' }).click()
  await expect(page.locator('.output-panel')).toContainText('送信できませんでした')
  await page.getByRole('button', { name: 'すべての音を停止' }).click()
  await expect(page.locator('.output-panel')).toContainText('停止メッセージを送信できませんでした')
  await page.evaluate(() => { window.midiTest.failSend = false })
  await page.getByRole('button', { name: '出力を再接続' }).click()
  await page.getByRole('button', { name: 'テスト音 C4' }).click()
  await expect(page.getByTestId('latest-output')).toContainText('Note Off')
  await page.evaluate(() => window.midiTest.send([0x90, 60, 80]))
  await expect(page.getByTestId('latest-input')).toContainText('C4')
  expect(await page.evaluate(() => window.midiTest.requests)).toBe(1)
  expect(errors).toEqual([])
})

test('reports missing output while input remains usable, then hotplugs using the same access', async ({ page }) => {
  await mockMidi(page)
  await page.goto('./')
  await page.evaluate(() => window.midiTest.setOutputConnected('cme-out', false))
  await page.getByRole('button', { name: 'MIDI接続', exact: true }).click()
  await expect(page.locator('.output-panel')).toContainText('MIDI出力機器が見つかりません')
  await expect(page.getByRole('button', { name: 'テスト音 C4' })).toBeDisabled()
  await page.getByRole('button', { name: '練習開始' }).click()
  await page.evaluate(() => window.midiTest.send([0x90, 60, 80]))
  await expect(page.locator('.position')).toHaveText('2 / 14 音')
  await page.evaluate(() => window.midiTest.setOutputConnected('cme-out', true))
  await expect(page.getByRole('button', { name: 'テスト音 C4' })).toBeEnabled()
  expect(await page.evaluate(() => window.midiTest.requests)).toBe(1)
})
