import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mockMidi } from './midiFixture'

const melody = [60, 60, 67, 67, 69, 69, 67, 65, 65, 64, 64, 62, 62, 60]
async function setup(page: Page) {
  await mockMidi(page)
  await page.goto('./')
  await expect(page.locator('.position')).toHaveText('1 / 14 音')
  await expect(page.getByRole('button', { name: '練習開始' })).toBeDisabled()
  await page.getByRole('button', { name: 'MIDI接続', exact: true }).click()
  await expect(page.locator('.midi-status')).toHaveText('MIDI 接続中')
}
async function send(page: Page, data: number[]) { await page.evaluate((data) => window.midiTest.send(data), data) }

test('correct presses move one note, mistakes and held duplicates stay, and releases never grade', async ({ page }) => {
  await setup(page)
  await page.getByRole('button', { name: '練習開始' }).click()
  await expect(page.locator('.practice-controls')).toHaveAttribute('data-practice-status', 'practicing')
  await send(page, [0x90, 64, 72])
  await expect(page.locator('.practice-feedback')).toHaveText('もう一度♪')
  await expect(page.locator('.position')).toHaveText('1 / 14 音')
  await send(page, [0x80, 64, 0])
  await send(page, [0x90, 60, 20])
  await expect(page.locator('.practice-feedback')).toHaveText('できた！')
  await expect(page.locator('.position')).toHaveText('2 / 14 音')
  await send(page, [0x90, 60, 96])
  await expect(page.locator('.position')).toHaveText('2 / 14 音')
  await send(page, [0x90, 60, 0])
  await expect(page.getByTestId('latest-input').locator('dd')).toHaveText(['60', '0', 'Note Off', '1'])
  await expect(page.locator('.position')).toHaveText('2 / 14 音')
  await send(page, [0x90, 60, 33])
  await expect(page.locator('.position')).toHaveText('3 / 14 音')
  await send(page, [0x80, 60, 40])
  await expect(page.locator('.position')).toHaveText('3 / 14 音')
  await expect(page.locator('.event-summaries')).toContainText('Velocity 33')
  await page.screenshot({ path: 'test-results/phase2b-practicing.png', fullPage: true })
})

test('a burst of fourteen strokes completes exactly once and restart works after completion', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await setup(page)
  await page.getByRole('button', { name: '練習開始' }).click()
  // All events occur before React can render another frame. A latest-event effect would lose them.
  await page.evaluate((notes) => {
    for (const note of notes) { window.midiTest.send([0x90, note, 72]); window.midiTest.send([0x80, note, 0]) }
  }, melody)
  await expect(page.locator('.position')).toHaveText('14 / 14 音')
  await expect(page.locator('.practice-feedback')).toHaveText('できました！')
  await expect(page.locator('.practice-controls')).toHaveAttribute('data-practice-status', 'completed')
  const cursor = page.locator('.score-renderer img')
  await expect(cursor).toBeVisible()
  const finalPosition = await cursor.evaluate((element) => (element as HTMLImageElement).style.cssText)
  await page.screenshot({ path: 'test-results/phase2b-completed.png', fullPage: true })
  await send(page, [0x90, 60, 96])
  await send(page, [0x90, 64, 72])
  await expect(page.locator('.position')).toHaveText('14 / 14 音')
  expect(await cursor.evaluate((element) => (element as HTMLImageElement).style.cssText)).toBe(finalPosition)
  await page.getByRole('button', { name: 'もう一度', exact: true }).click()
  await expect(page.locator('.position')).toHaveText('1 / 14 音')
  await expect(page.locator('.practice-feedback')).toHaveText('緑の帯の音を弾いてみよう')
  await send(page, [0x90, 60, 72])
  await expect(page.locator('.position')).toHaveText('1 / 14 音')
  await send(page, [0x80, 60, 0])
  await send(page, [0x90, 60, 72])
  await expect(page.locator('.position')).toHaveText('2 / 14 音')
  expect(errors).toEqual([])
})

test('start resets development navigation and restart resets in-progress feedback', async ({ page }) => {
  await setup(page)
  await expect(page.getByRole('button', { name: '次の音' })).toHaveCount(0)
  await page.getByText('開発者用', { exact: true }).click()
  await page.getByRole('button', { name: '次の音' }).click()
  await expect(page.locator('.position')).toHaveText('2 / 14 音')
  await page.getByRole('button', { name: '練習開始' }).click()
  await expect(page.locator('.position')).toHaveText('1 / 14 音')
  await expect(page.getByRole('button', { name: '次の音' })).toBeDisabled()
  await expect(page.getByRole('button', { name: '前の音' })).toBeDisabled()
  await send(page, [0x90, 60, 72])
  await send(page, [0x80, 60, 0])
  await send(page, [0x90, 64, 72])
  await expect(page.locator('.practice-feedback')).toHaveText('もう一度♪')
  await page.getByRole('button', { name: 'もう一度', exact: true }).click()
  await expect(page.locator('.position')).toHaveText('1 / 14 音')
  await expect(page.locator('.expected-note')).toContainText('MIDI Note 60')
  await expect(page.locator('.practice-feedback')).toHaveText('緑の帯の音を弾いてみよう')
  await page.setViewportSize({ width: 390, height: 844 })
  await send(page, [0x90, 60, 72])
  await expect(page.locator('.position')).toHaveText('2 / 14 音')
  await expect(page.locator('.score-renderer img')).toBeVisible()
})

test('a held key cannot advance at start and unplugging clears held state for reconnection', async ({ page }) => {
  await setup(page)
  await send(page, [0x90, 60, 72])
  await page.getByRole('button', { name: '練習開始' }).click()
  await send(page, [0x90, 60, 72])
  await expect(page.locator('.position')).toHaveText('1 / 14 音')
  await send(page, [0x80, 60, 0])
  await send(page, [0x90, 60, 72])
  await expect(page.locator('.position')).toHaveText('2 / 14 音')
  await page.evaluate(() => window.midiTest.setConnected('cme', false))
  await expect(page.locator('.practice-feedback')).toContainText('続きから弾けます')
  await expect(page.getByTestId('latest-input')).toHaveCount(0)
  await page.evaluate(() => window.midiTest.setConnected('cme', true))
  await expect(page.locator('.midi-status')).toHaveText('MIDI 接続中')
  await send(page, [0x90, 60, 72])
  await expect(page.locator('.position')).toHaveText('3 / 14 音')
})
